plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.74-beta'
}

tasks.named('wrapper', Wrapper) {
    gradleVersion = '8.8'
}

version = '1.0.0'
group = 'com.galadmitro.ragdollhandler'

base {
    archivesName = 'ragdollhandler'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = '21.1.65'

    parchment {
        mappingsVersion = '2024.07.28'
        minecraftVersion = '1.21.1'
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'ragdollhandler'
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'ragdollhandler'
        }
    }

    mods {
        ragdollhandler {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    // Links sable-neoforge-1.21.1-2.0.5.jar located in /libs
    implementation files("libs/sable-neoforge-1.21.1-2.0.5.jar")
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version: '1.21.1',
            minecraft_version_range: '[1.21.1,1.22)',
            neo_version: '21.1.65',
            neo_version_range: '[21.1,)',
            loader_version_range: '[2,)',
            mod_id: 'ragdollhandler',
            mod_name: 'Ragdoll Handler',
            mod_license: 'MIT',
            mod_version: version,
            mod_authors: 'galadmitro',
            mod_description: 'Ragdoll physics handler mod integrated with Sable.'
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}